craftics_cart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls)
]

main/urls.py
from django.urls import path
from . import views
from uuid import UUID
from main.views import show_main, create_craft_entry, show_xml, show_json, show_json_by_id, show_xml_by_id
from main.views import login_user, register, logout_user
from main.views import edit_craft, delete_craft
from main.views import add_craft_entry_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('create-craft-entry', create_craft_entry, name='create_craft_entry'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-craft/<uuid:id>', views.edit_craft, name='edit_craft'),
    path('delete/<uuid:id>', delete_craft, name='delete_craft'),
    path('add-craft-entry-ajax', add_craft_entry_ajax, name='add_craft_entry_ajax'),
]   

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Craft(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField(max_length=2000, default='')
    image_url = models.URLField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Craft
from django.utils.html import strip_tags
class CraftEntryForm(ModelForm):
    class Meta:
        model = Craft
        fields = ["name", "description", "price", "image_url"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)  # Strip HTML tags from craft name

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)  # Strip HTML tags from craft description

main/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from main.forms import CraftEntryForm
from main.models import Craft
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'nama' : request.user.username,
        'kelas': 'PBP F',
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

def create_craft_entry(request):
    form = CraftEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        craft_entry = form.save(commit=False)
        craft_entry.user = request.user
        craft_entry.save()
        return redirect('main:show_main')
    
    context = {'form': form}
    return render(request, "create_craft_entry.html", context)

def show_xml(request):
    data = Craft.objects.filter(user=request.user)    
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Craft.objects.filter(user=request.user)    
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Craft.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Craft.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New account created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_craft(request, id):
    # Get craft entry berdasarkan id
    craft = Craft.objects.get(pk = id)

    # Set craft entry sebagai instance dari form
    form = CraftEntryForm(request.POST or None, instance=craft)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_craft.html", context)

def delete_craft(request, id):
    # Get mood berdasarkan id
    craft = Craft.objects.get(pk = id)
    # Hapus mood
    craft.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_craft_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))  # strip HTML tags from craft name
    description = strip_tags(request.POST.get("description"))  # strip HTML tags from craft description
    name = request.POST.get("name")
    description = request.POST.get("description")
    price = request.POST.get("price")
    image_url = request.POST.get("image_url", "")  # Optional field, so we default to an empty string if not provided
    user = request.user

    # Creating a new CraftEntry object
    new_craft = Craft(
        name=name,
        description=description,
        price=price,
        image_url=image_url,  # If you are using image uploads, make sure to handle file data properly
        user=user
    )
    new_craft.save()

    # Return a success response
    return HttpResponse(b"CREATED", status=201)

main/templates/card_craft.html
{% load static %}

<div class="bg-white rounded-lg shadow-lg p-4 mb-6 w-full max-w-[18rem] mx-auto border-2 border-pink-500 relative">
  <!-- Image Section (Square) -->
  <div class="w-full h-auto aspect-square bg-pink-500 overflow-hidden rounded-lg mb-4">
    {% if craft_entry.image_url %}
      <!-- Render image from URL if provided -->
      <img src="{{ craft_entry.image_url }}" alt="Craft Image" class="w-full h-full object-cover">
    {% else %}
      <!-- Fallback to default image if no URL provided -->
      <img src="{% static 'image/default-card.png' %}" alt="Default Craft Image" class="w-full h-full object-cover">
    {% endif %}
  </div>
  
  <!-- Name of Craft -->
  <div class="text-center px-2">
    <h3 class="text-pink-500 text-lg font-bold mb-1">{{ craft_entry.name }}</h3>
    
    <!-- Description -->
    <p class="text-pink-500 text-sm italic mb-2">
      "{{ craft_entry.description }}"
    </p>
  </div>

  <!-- Price and Buttons Section -->
  <div class="flex justify-between mt-4">
    <!-- Price on the left -->
    <div class="bg-pink-500 text-white py-2 px-4 rounded-full font-bold">
      {{ craft_entry.price }}
    </div>

    <!-- Edit and Delete Buttons on the right -->
    <div class="flex space-x-2">
      <!-- Edit Button -->
      <a href="{% url 'main:edit_craft' craft_entry.pk %}" class="bg-yellow-400 hover:bg-yellow-500 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </a>
      
      <!-- Delete Button -->
      <a href="{% url 'main:delete_craft' craft_entry.pk %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</div>

main/templates/card_info.html
<div class="bg-white rounded-xl overflow-hidden shadow-lg border-2 border-pink-600">
  <div class="p-6">
    <h5 class="text-xl font-bold text-pink-500 text-center">{{ title }}</h5>
    <p class="text-gray-700 text-center mt-2">{{ value }}</p>
  </div>
</div>

main/templates/create_craft_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add Craft</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-pink-500">Create Craft Entry</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-pink-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Create Craft Entry
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Craftics Cart</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-yellow-100 flex flex-col justify-between">
  
  <!-- Carousel Section -->
  <div class="flex justify-center mb-8 relative">
    <div class="w-full max-w-4xl overflow-hidden relative border-4 border-pink-600 rounded-lg">
      <!-- Container Carousel -->
      <div id="carousel" class="flex transition-transform duration-500 ease-in-out w-[300%]">
        <img src="{% static 'image/car-1.png' %}" alt="Carousel 1" class="w-[100%] h-[450px] object-cover rounded-lg">
        <img src="{% static 'image/car-2.png' %}" alt="Carousel 2" class="w-[100%] h-[450px] object-cover rounded-lg">
        <img src="{% static 'image/car-3.png' %}" alt="Carousel 3" class="w-[100%] h-[450px] object-cover rounded-lg">
      </div>

      <!-- Tombol Geser Kiri -->
      <button id="prevBtn" class="absolute top-1/2 left-4 transform -translate-y-1/2 bg-white bg-opacity-50 text-gray-700 rounded-full p-3 z-20">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 24 24" fill="currentColor">
          <path fill-rule="evenodd" d="M15.293 7.293a1 1 0 011.414 1.414L10.414 15l6.293 6.293a1 1 0 01-1.414 1.414l-7-7a1 1 0 010-1.414l7-7z" clip-rule="evenodd" />
        </svg>
      </button>

      <!-- Tombol Geser Kanan -->
      <button id="nextBtn" class="absolute top-1/2 right-4 transform -translate-y-1/2 bg-white bg-opacity-50 text-gray-700 rounded-full p-3 z-20">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 24 24" fill="currentColor">
          <path fill-rule="evenodd" d="M8.707 16.707a1 1 0 01-1.414-1.414L13.586 9l-6.293-6.293a1 1 0 111.414-1.414l7 7a1 1 0 010 1.414l-7 7z" clip-rule="evenodd" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Craft Section -->
  <div class="flex flex-col items-center justify-center mb-8">
    <div id="craft_entry_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-gray-900">
            Add New Craft Entry
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="craftEntryForm">
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-gray-700">Craft Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-pink-500" placeholder="Enter craft name" required>
            </div>

            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-pink-500" placeholder="Describe the craft" required></textarea>
            </div>

            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
              <input type="number" id="price" name="price" min="1" step="0.01" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-pink-500" placeholder="Enter craft price" required>
            </div>

            <!-- New Image URL Input -->
            <div class="mb-4">
              <label for="image_url" class="block text-sm font-medium text-gray-700">Image URL</label>
              <input type="url" id="image_url" name="image_url" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-pink-500" placeholder="Enter image URL">
            </div>
          </form>
        </div>

        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitCraftEntry" form="craftEntryForm" class="bg-pink-600 hover:bg-pink-500 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>
   <!-- Nama dan Kelas di Bawah "+" Button -->
    <div class="text-center mt-6">
      <a href="{% url 'main:create_craft_entry' %}" class="relative group inline-block">
        <div class="flex items-center justify-center w-16 h-16 bg-pink-500 text-white rounded-full shadow-lg transition-all duration-300 transform group-hover:w-32 group-hover:bg-yellow-500 group-hover:scale-110">
          <span class="text-2xl font-bold group-hover:hidden">+</span>
          <span class="hidden group-hover:inline font-bold">Add Craft</span>
        </div>
      </a>
    </div>

    <!-- Add Craft by AJAX Button -->
    <div class="text-center mt-6">
      <div class="relative group inline-block">
        <div class="flex items-center justify-center w-16 h-16 bg-pink-500 text-white rounded-full shadow-lg transition-all duration-300 transform group-hover:w-32 group-hover:bg-yellow-500 group-hover:scale-110" onclick="showModal();">
          <span class="text-2xl font-bold group-hover:hidden">+</span>
          <span class="hidden group-hover:inline font-bold">Add Craft by AJAX</span>
        </div>
      </div>
    </div>


  <!-- Card Section -->
  <!-- <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 px-4 sm:px-6 lg:px-8">
    {% if craft_entries %}
      {% for craft_entry in craft_entries %}
        {% include 'card_craft.html' with craft_entry=craft_entry %}
      {% endfor %}
    {% endif %}
  </div> -->

  <!-- Timestamp di Paling Bawah -->
  <div class="text-center mt-8">
    <p class="text-gray-400 text-sm italic">Last Login: {{ last_login }}</p> <!-- Timestamp dengan sheer color -->
  </div>

  <!-- Nama dan Kelas -->
  <div class="text-center mt-6">
    <p class="text-pink-500 text-lg font-semibold"> &COPY; {{ nama }} || {{ kelas }}</p>
  </div>
</div>

<!-- Script Carousel -->
<script>
  const carousel = document.getElementById('carousel');
  const prevBtn = document.getElementById('prevBtn');
  const nextBtn = document.getElementById('nextBtn');
  let currentIndex = 0;

  // Total slides (jumlah gambar dalam carousel)
  const totalSlides = carousel.children.length;

  // Lebar per slide
  const slideWidth = carousel.children[0].clientWidth;

  // Geser ke kiri
  prevBtn.addEventListener('click', () => {
    if (currentIndex > 0) {
      currentIndex--;
      carousel.style.transform = `translateX(-${currentIndex * slideWidth}px)`;
    }
  });

  // Geser ke kanan
  nextBtn.addEventListener('click', () => {
    if (currentIndex < totalSlides - 1) {
      currentIndex++;
      carousel.style.transform = `translateX(-${currentIndex * slideWidth}px)`;
    }
  });
</script>

<script>
  // Fetch the list of craft entries as JSON
  async function getCraftEntries(){
      // Replace 'main:craft_entries_json' with the appropriate URL name in your Django urls.py
      return fetch("{% url 'main:show_json' %}").then((res) => res.json());
  }

  async function refreshCraftEntries() {
    document.getElementById("craft_entry_cards").innerHTML = "";
    document.getElementById("craft_entry_cards").className = "";
    const craftEntries = await getCraftEntries(); // Assuming getCraftEntries is already defined to fetch the craft entries.
    let htmlString = "";
    let classNameString = "";

    if (craftEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/bow.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">No crafts available in Craftics Cart.</p>
            </div>
        `;
    }
    else {
      classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 w-full"; // Reduced gap for smaller cards
      craftEntries.forEach((item) => {
        const name = DOMPurify.sanitize(item.fields.name);  // Sanitize the craft name
        const description = DOMPurify.sanitize(item.fields.description);  // Sanitize the craft description
          htmlString += `
          <div class="hover-shine bg-white rounded-lg shadow-lg p-1 mb-3 w-full max-w-[10rem] mx-auto border-2 border-pink-500">
              <!-- Image Section (Square) -->
              <div class="w-full h-auto aspect-square bg-pink-500 overflow-hidden rounded-lg mb-2">
                  <img src="${item.fields.image_url ? item.fields.image_url : '{% static "image/default-card.png" %}'}" alt="Craft Image" class="w-full h-full object-cover">
              </div>
              
              <!-- Name of Craft -->
              <div class="text-center px-1">
                  <h3 class="text-pink-500 text-sm font-bold mb-1">${item.fields.name}</h3>
                  
                  <!-- Description -->
                  <p class="text-pink-500 text-xs italic mb-1">
                      "${item.fields.description}"
                  </p>
              </div>

              <!-- Price Section -->
              <div class="flex justify-center mt-2">
                  <div class="bg-pink-500 text-white py-1 px-2 rounded-full font-bold text-xs">
                      Price: $${item.fields.price}
                  </div>
              </div>

              <!-- Edit and Delete Buttons -->
              <div class="flex justify-center space-x-2 mt-2">
                  <a href="/edit-craft/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full px-2 py-1 transition duration-300 shadow-md text-xs">
                      Edit
                  </a>
                  <a href="/delete/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full px-2 py-1 transition duration-300 shadow-md text-xs">
                      Delete
                  </a>
              </div>
          </div>
          `;
      });

    }
    document.getElementById("craft_entry_cards").className = classNameString;
    document.getElementById("craft_entry_cards").innerHTML = htmlString;
  }

  refreshCraftEntries();  // Call the function to load the entries

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      // Display the modal
      modal.classList.remove('hidden');
      setTimeout(() => {
          // Animate the modal content
          modalContent.classList.remove('opacity-0', 'scale-95');
          modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      // Reverse the animation before hiding the modal
      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
          // Hide the modal completely after the animation
          modal.classList.add('hidden');
      }, 150); 
  }

  // Add event listeners to hide modal on button clicks
  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  function addCraftEntry() {
    fetch("{% url 'main:add_craft_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#craftEntryForm')),  // Menggunakan form untuk Craft Entry
    })
    .then(response => refreshCraftEntries())  // Refresh daftar craft setelah craft ditambahkan

    // Reset form setelah submit berhasil
    document.getElementById("craftEntryForm").reset(); 

    // Tutup modal setelah penambahan item
    document.querySelector("[data-modal-toggle='crudModal']").click();

    return false;  // Mencegah default form submission
}

// Menghubungkan event submit dengan fungsi addCraftEntry
// document.getElementById("submitCraftEntry").onclick = addCraftEntry;
document.getElementById("craftEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addCraftEntry();
  })

</script>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<head>
  <!-- Menambahkan Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Poppins:wght@400;600&display=swap" rel="stylesheet">
</head>

<!-- Pastikan tag ini ditambahkan di bagian atas template -->
{% load static %}

<nav class="bg-pink-500 shadow-lg fixed top-0 left-0 z-40 w-screen font-poppins">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-20"> <!-- Sesuaikan tinggi navbar untuk mengakomodasi gambar yang lebih besar -->
      <!-- Logo / Brand -->
      <div class="flex items-center">
        <!-- Ganti teks dengan gambar logo -->
        <a href="/">
          <img src="{% static 'image/logo.png' %}" alt="Craftics Cart Logo" class="h-16 w-auto"> <!-- Ukuran diperbesar -->
        </a>
      </div>

      <!-- Navigation Links -->
      <div class="hidden md:flex items-center space-x-8 font-montserrat">
        {% if user.is_authenticated %}
          <span class="text-yellow-100">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="text-white hover:text-yellow-100 font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-white hover:text-yellow-100 font-bold py-2 px-4 rounded transition duration-300">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="text-white hover:text-yellow-100 font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>

      <!-- Mobile Menu Button -->
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>

<style>
  /* Menambahkan font Poppins dan Montserrat untuk navbar */
  .font-poppins {
    font-family: 'Poppins', sans-serif;
  }

  .font-montserrat {
    font-family: 'Montserrat', sans-serif;
  }

  /* Hover effect untuk navigasi */
  nav a:hover {
    text-decoration: underline;
  }
</style>